[package]

name = "twig"
version = "0.0.1"
description = "Twig templating engine for Rust; work in progress."
documentation = "http://nercury.github.io/twig-rs/twig/index.html"
repository = "https://github.com/Nercury/twig-rs"
authors = [
    "Nerijus Arlauskas <nercury@gmail.com>"
]
license = "MIT"

[dependencies]
regex = "*"
